# pedi auxilio a uma llm sobre como fazer um container que inicie antes do outro
# e como criar variáveis de ambiente 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iagorios
  name: playlist-recommendation-deployment
  labels:
    app: playlist-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-recommendation
  template:
    metadata:
      labels:
        app: playlist-recommendation
    spec:
      initContainers:
      - name: playlists-recommender-ml
        image: iagosrios/playlists-recommender-ml:0.1
        env:
        - name: DATASET_URL
          value: "https://github.com/iago-r/cloud_computing/raw/refs/heads/main/assets/datasets/2023_spotify_ds1.csv"
        volumeMounts:
        - name: models
          mountPath: /models
      containers:
      - name: playlists-recommender-frontend
        image: iagosrios/playlists-recommender-frontend:0.1
        ports:
        - containerPort: 52030
        env:
        - name: VERSION
          value: 0.0.1
        volumeMounts:
        - name: models
          mountPath: /models
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: project2-pv2-iagorios