# tive que consultar a llm, o fórum e tirar dúvidas com um amigo sobre como montar o volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: iagorios
  name: project2-pv2-iagorios
spec:
  volumeName: project2-pv2-iagorios
  storageClassName: default-storage-class-iagorios
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: iagorios