apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: iagorios
  name: project2-pv2-iagorios
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: iagorios
